eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8010/eureka/    
        instance:
            hostname: localhost

spring:
  datasource:
    url: jdbc:mysql://192.168.221.1:3306/microservices?autoReconnect=true
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
  jpa: 
    hibernate: 
      ddlAuto: update